Represent a machine learning dataset using vectors and matrices and perform basic linear algebra operations.

In [ ]:
# Import NumPy library for numerical computations
import numpy as np

# -----------------------------
# Representing a dataset
# -----------------------------
# Each row represents one data sample
# Each column represents one feature
# Example: [Height, Weight]
X = np.array([[160, 55],[170, 65],[180, 75]])

print("Dataset (Matrix X):")
print(X)

# -----------------------------
# Vector representation
# -----------------------------
# Extract the first sample as a vector
x1 = X[0]

print("\nFirst data sample (Vector x1):")
print(x1)

# -----------------------------
# Basic Linear Algebra Operations
# -----------------------------

# 1. Matrix Transpose
X_transpose = X.T
print("\nTranspose of X:")
print(X_transpose)

# 2. Vector addition
x2 = X[1]
vector_sum = x1 + x2
print("\nVector Addition (x1 + x2):")
print(vector_sum)

# 3. Scalar multiplication
scaled_vector = 2 * x1
print("\nScalar Multiplication (2 * x1):")
print(scaled_vector)

# 4. Dot product of two vectors
dot_product = np.dot(x1, x2)
print("\nDot Product of x1 and x2:")
print(dot_product)

# 5. Matrix multiplication
# Multiply dataset with its transpose
matrix_product = np.dot(X, X_transpose)
print("\nMatrix Multiplication (X · Xᵀ):")
print(matrix_product)


Dataset (Matrix X):
[[160  55]
 [170  65]
 [180  75]]

First data sample (Vector x1):
[160  55]

Transpose of X:
[[160 170 180]
 [ 55  65  75]]

Vector Addition (x1 + x2):
[330 120]

Scalar Multiplication (2 * x1):
[320 110]

Dot Product of x1 and x2:
30775

Matrix Multiplication (X · Xᵀ):
[[28625 30775 32925]
 [30775 33125 35475]
 [32925 35475 38025]]


📌 Explanation (in simple words)

Matrix X → Represents the entire dataset

Vector x1 → Represents one data point

Transpose → Converts rows into columns

Dot product → Measures similarity between two vectors

Matrix multiplication → Used in ML models for feature interactions