Example: Linear Transformation of Feature Embeddings

Idea

Each row of the matrix = one data point (embedding)

Columns = features

A linear transformation is applied using matrix multiplication

In [ ]:
import numpy as np

# -----------------------------
# Step 1: Create sample data
# -----------------------------
# Each row represents a data point
# Each column represents a feature
X = np.array([
    [2, 1],
    [1, 3],
    [4, 2]
])

print("Original Feature Embeddings:")
print(X)

# -----------------------------
# Step 2: Define a linear transformation matrix
# -----------------------------
# This matrix will transform the feature space
# Example: rotation + scaling effect
W = np.array([
    [1, 2],
    [0, 1]
])

print("\nTransformation Matrix:")
print(W)

# -----------------------------
# Step 3: Apply linear transformation
# -----------------------------
# Matrix multiplication
X_transformed = X @ W

print("\nTransformed Feature Embeddings:")
print(X_transformed)

# -----------------------------
# Step 4: Compare original vs transformed
# -----------------------------
for i in range(len(X)):
    print(f"\nData Point {i+1}:")
    print("Original   :", X[i])
    print("Transformed:", X_transformed[i])


Original Feature Embeddings:
[[2 1]
 [1 3]
 [4 2]]

Transformation Matrix:
[[1 2]
 [0 1]]

Transformed Feature Embeddings:
[[ 2  5]
 [ 1  5]
 [ 4 10]]

Data Point 1:
Original   : [2 1]
Transformed: [2 5]

Data Point 2:
Original   : [1 3]
Transformed: [1 5]

Data Point 3:
Original   : [4 2]
Transformed: [ 4 10]


**Define how features are mixed or scaled. The relative structure may rotate or scaled**

**Common in PCA, NEURAL NETWORKS,SVM and deep learning layers**

**Linear transformations modifies feature embeddings by mapping the data points into a new feature space using matrix multiplication while preserving linear relationships**