Implement Principal Component Analysis (PCA) using covariance matrices for dimensionality reduction.

In [ ]:
import numpy as np

# -----------------------------
# Step 1: Create a sample dataset
# Rows = samples, Columns = features
# -----------------------------
X = np.array([[2, 3],
              [3, 4],
              [4, 5],
              [5, 6],
              [6, 7]])

# -----------------------------
# Step 2: Mean centering the data
# Subtract the mean of each feature
# -----------------------------
mean = np.mean(X, axis=0)
X_centered = X - mean

# -----------------------------
# Step 3: Compute covariance matrix
# rowvar=False -> columns represent features
# -----------------------------
cov_matrix = np.cov(X_centered, rowvar=False)

# -----------------------------
# Step 4: Compute eigenvalues and eigenvectors
# Eigenvectors = principal directions
# -----------------------------
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# -----------------------------
# Step 5: Sort eigenvectors by descending eigenvalues
# -----------------------------
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

# -----------------------------
# Step 6: Select top k principal components
# Here k = 1 (dimensionality reduction to 1D)
# -----------------------------
k = 1
principal_components = eigenvectors[:, :k]

# -----------------------------
# Step 7: Project data onto principal components
# Reduced dimensional data
# -----------------------------
X_reduced = X_centered @ principal_components

# -----------------------------
# Print results
# -----------------------------
print("Original Data:\n", X)
print("\nCovariance Matrix:\n", cov_matrix)
print("\nPrincipal Component:\n", principal_components)
print("\nReduced Data:\n", X_reduced)


Original Data:
 [[2 3]
 [3 4]
 [4 5]
 [5 6]
 [6 7]]

Covariance Matrix:
 [[2.5 2.5]
 [2.5 2.5]]

Principal Component:
 [[0.70710678]
 [0.70710678]]

Reduced Data:
 [[-2.82842712]
 [-1.41421356]
 [ 0.        ]
 [ 1.41421356]
 [ 2.82842712]]


🔑 What this code demonstrates (exam-oriented)

Mean centering of data

Covariance matrix computation

Eigen decomposition

Selection of principal components

Projection to lower dimensions

📌 One-line explanation for practical record

PCA reduces dimensionality by projecting data onto eigenvectors of the covariance matrix corresponding to the largest eigenvalues.