In [ ]:
#create a vector
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#create a matrix
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#vector addition
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [ ]:
#matrix addition
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=a+b
print(c)

In [ ]:
#multiplication (dot product vectors)
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c= np.dot(a,b)
print(c)

32


In [ ]:
#scalar multiplication-vector
import numpy as np
a=np.array([1,2,3])
b=2*a
print(b)

[2 4 6]


In [ ]:
#matrix multiplication
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[9,10],[11,12]])
c=np.dot(a,b)
print(c)

[[ 58  64]
 [139 154]]


In [ ]:
#transpose of matrix
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
#b=a.T
b = np.transpose(a)
print(b)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Euclidean Norm (L2 Norm)--
#usual distance between the origin and the point represented by vector
import numpy as np
a=np.array([3,4])
b=np.linalg.norm(a)
print(b)


5.0


In [ ]:
#manhattan norm (L1 norm)
import numpy as np
a=np.array([3,4])
b=np.linalg.norm(a,ord=1)
print(b)

In [ ]:
#infinity norm
import numpy as np
a=np.array([3,4])
b=np.linalg.norm(a,ord=np.inf)
print(b)

In [ ]:
import numpy as np

A = np.array([[2, 0],
              [0, 2]])

x = np.array([1, 3])

Tx = A @ x
print("Result after linear operator:", Tx)


Result after linear operator: [2 6]


In [ ]:
import numpy as np
A = np.array([[2, 0],
              [0, 2]])
x = np.array([1, 3])
y = np.array([2, 1])
left = A @ (x + y)
right = (A @ x) + (A @ y)
print("Left:", left)
print("Right:", right)


Left: [6 8]
Right: [6 8]


1. Scaling
Scaling is a linear transformation that enlarges or shrinks the vectors by a scalar factor.


In [ ]:
import numpy as np

# Scaling matrix
scale_factor = 2
scaling_matrix = np.array([[scale_factor, 0],
                           [0, scale_factor]])
# Original vector
vector = np.array([1, 2])
# Applying scaling
scaled_vector = scaling_matrix @ vector
print("Scaled Vector:", scaled_vector)


Scaled Vector: [2 4]



2. Rotation
Rotation is a linear transformation that rotates vectors by a specified angle.


In [ ]:
import numpy as np

# Rotation angle (in radians)
theta = np.pi / 4  # 45 degrees

# Rotation matrix
rotation_matrix = np.array([[np.cos(theta), -np.sin(theta)],
                            [np.sin(theta), np.cos(theta)]])

# Original vector
vector = np.array([1, 0])

# Applying rotation
rotated_vector = rotation_matrix @ vector
print("Rotated Vector:", rotated_vector)


Rotated Vector: [0.70710678 0.70710678]


3. Reflection
Reflection is a linear transformation that flips vectors over a specified axis.


In [ ]:
import numpy as np

# Reflection matrix (over y-axis)
reflection_matrix = np.array([[-1, 0],
                              [0,  1]])

# Original vector
vector = np.array([1, 2])

# Applying reflection
reflected_vector = reflection_matrix @ vector
print("Reflected Vector:", reflected_vector)


Reflected Vector: [-1  2]
