In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])

print(arr, type(arr), arr.dtype, arr.shape)
arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape )

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)


In [8]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print(arr2d,  arr2d.shape, arr2d.dtype, type(arr2d))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3) int64 <class 'numpy.ndarray'>


In [5]:
# creating 

arr0 = np.zeros((2,3), dtype = "int64") # prefill with zeroes
print(arr0)

arr1 = np.ones((2,5), dtype = "int64") # prefill with ones
print(arr1)

arr2 = np.full((3,4),100)             # prefill with value
print(arr2)

arr3 = np.eye((4))                    # indentity matrix
print(arr3)

arr4 = np.arange(0,11,2)              # range elements
print(arr4)

arr5 = np.linspace(1, 101, 3)        # evenly spaced array 
print(arr5)

[[0 0 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 0  2  4  6  8 10]
[  1.  51. 101.]


In [6]:
# properties of array

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) # dimensions = m x n 
print(arr.size) # total elements
print(arr.dtype) #type 
print(arr.ndim) # dimenstion of array 

float_arr = arr.astype(np.float64)
print(float_arr) # type conversion 

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [9]:
# operation on numpy array 
# reshape an array into different dimensions 
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

reshape = arr.reshape((3,2))
print(reshape)

flattened = arr.flatten() # to flatten array into 1D array  
print(flattened)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [10]:
#indexing array (1D and 2D array)
#accessing array using index 

arr = np.array([1,2,3,4,5,6])
print(arr[0]) # accessing array using index
print(arr[3]) # accessing array using index

arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d[0,2]) # accessing array using 2D array 

# fancy indexing 
fancy_arr = np.array([1,2,3,4,5,6,7,8])

idx = [1,3,6] # accessing different array elements at once using fancy indexing  
print(fancy_arr[idx])
# boolean indexing 

bool_arr = np.array([1,2,3,4,5,6,7])
print(bool_arr[bool_arr % 2 != 0]) # print values greater then given value 
print(bool_arr[bool_arr > 0]) # print values greater then given value 

1
4
3
[2 4 7]
[1 3 5 7]
[1 2 3 4 5 6 7]


In [11]:
# slicing 
arr = np.array([1,2,3,4,5,6])

print(arr[1:5:2])
print(arr[1:])

print(arr[:4])
print(arr[::2])

[2 4]
[2 3 4 5 6]
[1 2 3 4]
[1 3 5]


In [12]:
 # copy vs view
nums = [1,2,3,4,5,6,7,8]
sub_list = nums[1:5]
print(sub_list)
sub_list[0] = 100
print(sub_list)
print(nums)

[2, 3, 4, 5]
[100, 3, 4, 5]
[1, 2, 3, 4, 5, 6, 7, 8]


In [13]:
# numpy Data types common
# int 32, int64
#  float 32, float 64
# boolean bool 
# complex nums complex64, complex32
# String S and U
# object 

arr = np.array([1,2,3,4,5,6,7,8.5, "XYZ", True]) 
# if one values is float, String all the values will be converted into float, string 
print(arr, arr.dtype)

comp = np.array([3+5j])
print(comp)



['1' '2' '3' '4' '5' '6' '7' '8.5' 'XYZ' 'True'] <U32
[3.+5.j]


In [14]:
# Axes in multi-dimensional array 

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

print(np.sum(arr2d)) # sum of all the elements 
sum_of_colums = np.sum(arr2d, axis = 0) # sum of colums 
#sum of all the colums (if 1 then left to right sum, 0 then top to bottum )
print(sum_of_colums)
sum_of_row = np.sum(arr2d, axis = 1) # sum of row
#sum of all the colums (if 1 then left to right sum, 0 then top to bottum )
print(sum_of_row)

print(arr2d[0:3, 1:3]) # slicing the value in an array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]
 [8 9]]


In [15]:
# 3D array 

arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) # size = 2 X 3 X 2
print(arr3d, arr3d.shape)

# indexing

print(arr3d[1,0,0]) # accessing the elements using the slicing
# first number define the array block either 1 or 0 
# second number define the row number here 0 or 1 or 2
# third number define the index of the number here 0 or 1
print(arr3d[0,1,]) # got value present at first block second layer both the values

print(arr3d[:,1,:]) # will get values present at the first index from both the block 

print(arr3d[:,:,0]) # get all the colums from the array 

arr3d[:,:,0] = 69 # changing the values 
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
7
[3 4]
[[ 3  4]
 [ 9 10]]
[[ 1  3  5]
 [ 7  9 11]]
[[[69  2]
  [69  4]
  [69  6]]

 [[69  8]
  [69 10]
  [69 12]]]


In [16]:
# vectorization

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,2,3,4,5,6])
# print(arr1 ++ 2)
# print(arr1 + 90)
# print(arr1 + arr2)

# Broadcasting
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arr1 + arr2)
print(arr1.shape)
print(arr2.shape)

[[ 2  4  6  8 10 12]
 [ 2  4  6  8 10 12]]
(6,)
(2, 6)


In [24]:
# vector normalization

arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
print(mean)
# mean = sum of values / number of values
std_ary = np.std(arr)

normalization_array = (arr - mean) / std_ary
print(normalization_array)




2.5
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [38]:
# important mathemtical function in numpy 

arr = np.array([1,2,3,4,5])

sum_arr = np.sum(arr) # sum of all the value 

product_arr = np.prod(arr) # product of all the values 

min_value = np.min(arr) # minimum value in an index

max_value = np.max(arr) # maximum value in an index

arg_min = np.argmin(arr) # return the index of the value we are providing

arg_max = np.argmax(arr) # return the index of the value we are providing

mean_arr = np.mean(arr) # return the mean from the array 

std_devi = np.std(arr) # return the standard deivatation of the array 

median_arr = np.median(arr) # return the median of the array 

variance_arr = np.var(arr) # return the variance of the array 


2.0


In [45]:
# power function 

arr = np.array([1,2,3,4,5])

squ = np.square(arr) # square of all the value 

sq_rt = np.sqrt(arr) # for square root of all the values

power = np.pow(arr, 2) # return the power of all define by the user


In [48]:
# log 
arr = np.array([1,2,3,4,5])

ntr_log = np.log(arr) # for natural log for all the values

log_base10 = np.log10(arr) # log 10 for all the values

log_base2 = np.log2(arr) # log 2 for all the values

exp_arr = np.exp(arr) # for expoential values 

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
