In [1]:
import numpy as np
import time
import sys

In [2]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a,b)

[1 2 3 4] [5 6 7 8]


In [5]:
v = np.array([1,2,3,4]) # vectors
print(v.shape)

m = np.array([[1,2],[3,4],[5,6]])
print(m.shape)

(4,)
(3, 2)


In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Shape: ", arr.shape)
print("Dimensions: ",arr.ndim)
print("Total Elements: ",arr.size)
print("Data Type: ",arr.dtype)

Shape:  (3, 1)
Dimensions:  2
Total Elements:  3
Data Type:  int64


In [6]:
np.zeros((3,3)) # add zeros in a 3x3 matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3)) # add ones in nxn matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.eye(3) # make a digonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
np.full((3,4),100) # prefill with values

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [10]:
np.linspace(0,1,6) # divide number from given range with a n number of partations

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [11]:
arr = np.array([10,20,30,40,50])
print(arr[2]) # print using index
print(arr[1:4]) # printing from n to n index (1D)

30
[20 30 40]


In [12]:
m = np.array([[1,2,3],
              [4,5,6]])

print(m[0,1])      # element
print(m[:,1])      # full column
print(m[1,:])      # full row


2
[2 5]
[4 5 6]


In [13]:
arr = np.arange(9) # giving a range from 0 to n
reshape = arr.reshape(3,3) # defining shape of the matrix
print(reshape) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
a = np.array([1,2,3,4,5])

print(a + 5) # adding 5 into all the values
print(a * 2) # multiplying all the values with 2
print(a ** 2) # squareing all the values

[ 6  7  8  9 10]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [15]:
# Aggregation Functions (1D array)

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))

15
3.0
1.4142135623730951
5
1


In [16]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(np.mean(m, axis=0))  # column-wise
print(np.mean(m, axis=1))  # row-wise


[4. 5. 6.]
[2. 5. 8.]


In [17]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(np.dot(a,b))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [18]:
import numpy as np

# dataset: rows = students, columns = [math_score, physics_score]
X = np.array([[80, 90],
              [70, 85],
              [60, 75],
              [90, 95]])

mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_normalized = (X - mean) / std

print("Original Data:\n", X)
print("Mean:", mean)
print("Standard Deviation:", std)
print("Normalized Data:\n", X_normalized)

Original Data:
 [[80 90]
 [70 85]
 [60 75]
 [90 95]]
Mean: [75.   86.25]
Standard Deviation: [11.18033989  7.39509973]
Normalized Data:
 [[ 0.4472136   0.50709255]
 [-0.4472136  -0.16903085]
 [-1.34164079 -1.52127766]
 [ 1.34164079  1.18321596]]


In [19]:
import numpy as np

# data
X = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

# compute slope and intercept manually
mean_x = np.mean(X)
mean_y = np.mean(y)

numerator = np.sum((X - mean_x) * (y - mean_y))
denominator = np.sum((X - mean_x)**2)

m = numerator / denominator
b = mean_y - m * mean_x

print("Slope:", m)
print("Intercept:", b)

Slope: 2.0
Intercept: 0.0


In [59]:
size = 1_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()

print(f"Python list time {end-start} second")

Python list time 0.11811494827270508 second


In [60]:
size = 1_000_000
np_arr = np.array(size)
start = time.time()

sq_arr = np_arr ** 2
end = time.time()
print(f"Numpy list time {end-start} second")

Numpy list time 0.00014448165893554688 second


In [61]:
print(f"Python list size = {sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"Numpy list size = {np_arr.nbytes} bytes")

Python list size = 8000056000000 bytes
Numpy list size = 8 bytes


In [3]:
# create numpy array 
# 1D array
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1,2,3,4,5,"Cherry"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

# 2D array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D) # 3 X 3 array


[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'Cherry'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
np.arange(0,11,2) # print number from n to n with n space last value excluded

array([ 0,  2,  4,  6,  8, 10])

In [8]:
# properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
float_arr # as type to change the type of array

(3, 3)
9
int64
2


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [15]:
# Operation on array

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

reshape = arr.reshape((3,2))
print(reshape) # reshaping only possible when size is comptable 

flattend = arr.flatten()
print(flattend) # array will be flattend

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [2]:
# Indexing
arr = np.array([1,2,3,4,5])

# Accessing using index
print(arr[3])
print(arr[0])

# slicing
print(arr[:3])
print(arr[::])
print(arr[1:])

# fancy indexing
idx = [0,2,4]
print(arr[idx])

# boolean indexing 
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[arr > 5])
print(arr[arr % 2 == 0])
print(arr[arr % 2 !=0 ])

4
1
[1 2 3]
[1 2 3 4 5]
[2 3 4 5]
[1 3 5]
[6 7 8]
[2 4 6 8]
[1 3 5 7]


In [4]:
# data types 
arr = np.array([1,2,3,4.5, "Cherry"])
arr

array(['1', '2', '3', '4.5', 'Cherry'], dtype='<U32')

In [8]:
arr1 = np.array([3+5j])
arr2 = np.array([2+6j])
print(arr1+arr2)
print(arr1/arr2)
print(arr1-arr2)

[5.+11.j]
[0.9-0.2j]
[1.-1.j]


In [21]:
# Multi-Dimensions array 

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

print(np.sum(arr2d))
print(np.sum(arr2d,axis=0)) # sum of all the calumns
print(np.sum(arr2d,axis=1)) # sum of all the rows 
print(arr2d[0:2,1:2]) # accessing using slicing

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [41]:
# 3D array
arr3D = np.array([[[1,2],[3,4],[5,6]]
                  ,[[7,8],[9,10],[11,12]]]) # 2 x 3 x 2
print(arr3D, arr3D.shape)

# indxing

print(arr3D[0,1,1])
print(arr3D[1,0,1])
# first number - block
# second number - columns
# third number - row

# slicing
print(arr3D[:,:,0])
print(arr3D[0,:,1]) == 99

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
8
[[ 1  3  5]
 [ 7  9 11]]
[2 4 6]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
# Vectorization 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
print(arr1 ** 2)
print(arr1 ++ 3)
print(arr1 + arr2)

# Braodcasting - scaling
arr3 = np.array([1,2,3,4,5])
arr4 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr -+ 4)

[ 1  4  9 16 25]
[4 5 6 7 8]
[ 2  4  6  8 10]
[-3 -2 -1  0  1]


In [20]:
# Vector normalization

arr = np.array([1,2,3,4])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr - mean) / std_dev
print(normalized_arr)



[-1.34164079 -0.4472136   0.4472136   1.34164079]


In [21]:
arr = np.array([1,2,3,4,5,6])

In [27]:
# power function 
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,4))

[ 1  4  9 16 25 36]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[   1   16   81  256  625 1296]


In [31]:
# log 
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [36]:
# Rounding of values
print(np.round(3.24))
print(np.ceil(3.14))
print(np.floor(3.234))
print(np.trunc(234.34))
print(np.unique(arr))

3.0
4.0
3.0
234.0
[1 2 3 4 5 6]
