In [1]:
import numpy as np

In [173]:
# ----------------------PROJECT 1----------------------
# ----------------------DATA PART----------------------
# Student names
students = np.array(['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'])

# Subject names
subjects = np.array(['Math', 'English', 'Science', 'History'])

# 2D array: 10 students × 4 subjects (scores 0-100)
# Each row = one student, Each column = one subject
grades = np.array([
    [85, 78, 92, 88],      # Alice
    [76, 82, 79, 85],      # Bob
    [92, 88, 95, 91],      # Charlie
    [88, 91, 67, 89],      # Diana
    [78, 75, 80, 77],      # Eve
    ])

# print("Students:", students)
# print("Subjects:", subjects)
# print("\nGrades Array (5 students × 4 subjects):")
# print(grades)
# ----------------------CALCULATION PART----------------------

student_average = grades.mean(axis = 1)
subject_average = grades.mean(axis = 0)
# min_avgerage = grades.mean(axis = 0)

print("Average of Each Student.")
for i in range(len(students)):
    print(f"{students[i]} Average is: {student_average[i]}")
    
max_average_class = np.max(student_average)
max_average_subject = np.max(subject_average)
min_average_subject = np.min(subject_average)
print(50*"-")
print("Calculaing Average.")
print(f"Highest Average in the Class: {max_average_class}")
print(f"Highest Average in the subject: {max_average_subject}")
print(f"Lowest Average in the subject: {min_average_subject}")
print(50*"-")

student_passed_or_not = np.all(grades >= 70, axis = 1)
print("List of passed and Failed Students.")
for i in range(len(students)):
    if student_passed_or_not[i]:
        print(f"{students[i]} is Passed with {student_average[i]}.")
    else:
        print(f"{students[i]} is Failed with {student_average[i]}.")

    

Average of Each Student.
Alice Average is: 85.75
Bob Average is: 80.5
Charlie Average is: 91.5
Diana Average is: 83.75
Eve Average is: 77.5
--------------------------------------------------
Calculaing Average.
Highest Average in the Class: 91.5
Highest Average in the subject: 86.0
Lowest Average in the subject: 82.6
--------------------------------------------------
List of passed and Failed Students.
Alice is Passed with 85.75.
Bob is Passed with 80.5.
Charlie is Passed with 91.5.
Diana is Failed with 83.75.
Eve is Passed with 77.5.


In [62]:
# ----------------------PROJECT 2----------------------

Stores = np.array(["Store A", "Store B", "Store C"])
Categories = np.array(["Electronic","Clothing","Groceries","Home & Garden"])
Months = np.array(["january","February","March"])
# Each value is the sales amount in thousands of dollars "$"
sales_data = np.array([
    [
    # January data
      [8900,7000,9000,6000],#Store A
      [6000,9007,8000,5000],#Store B
      [3001,9001,5100,9000],#store C 
    ],
    [
    # February data
      [9000,8000,7000,4001],#Store A
      [6600,9001,7800,2100],#Store B
      [3004,7002,5100,3100],#store C 
    ],
    [
    # March datasho
      [4900,7300,9100,1000],#Store A
      [6000,9700,8000,4000],#Store B
      [1000,1900,6001,7000],#store C 
    ]
])

# Calculate total sales per store (across all months and categories)
monthly_collection = np.sum(sales_data,axis=2)
categories_collection = np.sum(sales_data,axis=1)
monthly_collect = np.sum(monthly_collection,axis=1)
most_revenue = np.max(monthly_collect)
print(f"Collection of Store (Months): {monthly_collect}")
print(f"Collection of Store (Categories): {np.sum(categories_collection,axis=0)}")
print(f"Most Revenue Made: {most_revenue}")
print("-"*50)

# Calculate total sales per product category (across all months and stores)
# Calculate total sales per month (across all stores and categories)
total_sales_categories = np.sum(sales_data,axis=1)
total_month = np.sum(monthly_collection,axis=1)
total_cate = np.sum(total_sales_categories,axis=0)
higest_sales = np.max(total_month)
higest_cate = np.max(total_cate)
print(f"Total Sales Per Month: {total_month}")
print(f"Total Sales in Catogeries: {total_cate}")
print(f"highest sales in a Month: {higest_sales}")
print(f"highest sales in categorie: {higest_cate}")
print("-"*50)

# Find the highest and lowest single sale record
print(f"higest in Collection in a Month: {np.max(sales_data)}")
print(f"Lowest in Collection in a Month: {np.min(sales_data)}")
print("-"*50)

# Calculate average sales for each store per month
average_sales_per_month = np.mean(sales_data, axis=2)
print(f"Average sales for each store per month \n{average_sales_per_month}")

Collection of Store (Months): [85009 71708 65901]
Collection of Store (Categories): [48405 67911 65101 41201]
Most Revenue Made: 85009
--------------------------------------------------
Total Sales Per Month: [85009 71708 65901]
Total Sales in Catogeries: [48405 67911 65101 41201]
highest sales in a Month: 85009
highest sales in categorie: 67911
--------------------------------------------------
higest in Collection in a Month: 9700
Lowest in Collection in a Month: 1000
--------------------------------------------------
average sales for each store per month 
[[7725.   7001.75 6525.5 ]
 [7000.25 6375.25 4551.5 ]
 [5575.   6925.   3975.25]]


In [40]:
# ----------------------PROJECT 3----------------------
original_data = np.array([  47, 3, 89, 12, 65, 28, 94, 51, 7, 36, 
                            22, 80, 14, 99, 41, 55, 67, 9, 73, 30, 
                            18, 92, 44, 6, 25, 77, 33, 11, 62, 85, 
                            39, 20, 56, 70, 2, 48, 13, 95, 31, 60, 
                            16, 74, 27, 81, 46, 5, 68, 34, 10, 53, 
                            19, 88, 23, 40, 71, 8, 63, 29, 97, 15, 
                            50, 4, 76, 21, 38, 66, 17, 83, 26, 59, 
                            32, 90
                         ])
# Task 1: Reshaping Data
reshape_6x12 = original_data.reshape((6,12))
print(f"Reshape data into 6, 12:\n {reshape_6x12}")
reshape_2x3x12 = original_data.reshape((2,3,12))
print(f"Reshape data into 2, 3, 12:\n {reshape_2x3x12}")
flatten_72 = original_data.flatten()
print(f"flattened data into 72: {flatten_72}")
print("-"*50)

Reshape data into 6, 12:
 [[47  3 89 12 65 28 94 51  7 36 22 80]
 [14 99 41 55 67  9 73 30 18 92 44  6]
 [25 77 33 11 62 85 39 20 56 70  2 48]
 [13 95 31 60 16 74 27 81 46  5 68 34]
 [10 53 19 88 23 40 71  8 63 29 97 15]
 [50  4 76 21 38 66 17 83 26 59 32 90]]
Reshape data into 2, 3, 12:
 [[[47  3 89 12 65 28 94 51  7 36 22 80]
  [14 99 41 55 67  9 73 30 18 92 44  6]
  [25 77 33 11 62 85 39 20 56 70  2 48]]

 [[13 95 31 60 16 74 27 81 46  5 68 34]
  [10 53 19 88 23 40 71  8 63 29 97 15]
  [50  4 76 21 38 66 17 83 26 59 32 90]]]
flattened data into 72: [47  3 89 12 65 28 94 51  7 36 22 80 14 99 41 55 67  9 73 30 18 92 44  6
 25 77 33 11 62 85 39 20 56 70  2 48 13 95 31 60 16 74 27 81 46  5 68 34
 10 53 19 88 23 40 71  8 63 29 97 15 50  4 76 21 38 66 17 83 26 59 32 90]
--------------------------------------------------


In [41]:
# Task 2: Broadcasting - Temperature Data

Temperature_Readings = np.array([[25.5, 26.0, 25.8, 26.2],
                                 [30.1, 30.5, 30.2, 30.8],
                                 [22.3, 22.5, 22.1,22.9]])
baseline_temperature = np.array([25.0, 30.0, 22.0]).reshape(3,1)
Difference_Temperature =  Temperature_Readings - baseline_temperature
print(f"Original Temperature Reading: \n{Temperature_Readings}")
print(f"BaseLine Temperature Reading: \n{baseline_temperature}")
print(f"Temperature Difference after baseline Deduction: \n{Difference_Temperature}")
print(f"Shape of the result Data: {Difference_Temperature.shape}")

Original Temperature Reading: 
[[25.5 26.  25.8 26.2]
 [30.1 30.5 30.2 30.8]
 [22.3 22.5 22.1 22.9]]
BaseLine Temperature Reading: 
[[25.]
 [30.]
 [22.]]
Temperature Difference after baseline Deduction: 
[[0.5 1.  0.8 1.2]
 [0.1 0.5 0.2 0.8]
 [0.3 0.5 0.1 0.9]]
Shape of the result Data: (3, 4)


In [80]:
# Task 3: Advanced Boolean Indexing - Filter Abnormal Readings
sensor_data = np.array([45, 67, 23, 89, 12, 34, 56, 78, 90, 11, 22, 33, 95, 44, 76, 88])
# print(sensor_data.size)
count_abnormal_reading = sensor_data[sensor_data > 75]
Readings_in_Normal = sensor_data[(sensor_data <= 70) & (sensor_data >= 30)] 
conditional_replacement = np.where(sensor_data > 85, 85, sensor_data)
print(f"Original Data: {sensor_data}")
print(f"Filtered Data: {count_abnormal_reading}")
print(f"Count of Abnormal readings: {count_abnormal_reading.size}")
print(f"Readings between 30 and 70: {Readings_in_Normal}")
print(f"Count of Normal readings: {Readings_in_Normal.size}")
print(f"After clipping values > 85 to 85: {conditional_replacement}")

Original Data: [45 67 23 89 12 34 56 78 90 11 22 33 95 44 76 88]
Filtered Data: [89 78 90 95 76 88]
Count of Abnormal readings: 6
Readings between 30 and 70: [45 67 34 56 33 44]
Count of Normal readings: 6
After clipping values > 85 to 85: [45 67 23 85 12 34 56 78 85 11 22 33 85 44 76 85]
